package com.example.demo.enums;

public enum MessageEnum {
    DATA_NOT_FOUND,
    USE_CORRECT_METHOD,
    SEND_PROPER_FIRST_NAME,
    SEND_PROPER_LAST_NAME,
    LOGGED_IN,
    LOGGED_OUT,
    SUCCESS_DELETE,
    SUCCESS_UPDATED,
    FOUND_ALL_USERS,
    SUCCESS_CREATE_ACCOUNT,
    EMAIL_ALREADY_USED,
    PASSWORD_STRENGTH_WEAK,
    GIVEN_DETAILS_ARE_ILLEGAL,
    PASSWORD_NOT_MATCH,
    EMAIL_NOT_VALID,
    SEND_PROPER_PASSWORD,
    NO_USERS,
    NOT_LOGGED_IN,
    NOT_AUTHORIZED,
    ALREADY_LOGGED_IN;

}
